Controllers/ServiceReportController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebENG.Interface;
using WebENG.Models;
using WebENG.Service;

namespace WebENG.Controllers
{
    public class ServiceReportController : Controller
    {
        readonly IAccessory Accessory;
        private IJob Job;
        readonly IDailyReport DailyReport;
        private IExport Export;
        readonly CTLInterfaces.IEmployee Employees;
        private readonly IHostingEnvironment _hostingEnvironment;
        static string _job = "";
        public ServiceReportController(IHostingEnvironment hostingEnvironment)
        {
            Accessory = new AccessoryService();
            Job = new JobService();
            DailyReport = new DailyReportService();
            Export = new ExportService();
            Employees = new CTLServices.EmployeeService();
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Login_ENG") != null)
            {
                string user = HttpContext.Session.GetString("userId");

                List<UserModel> users = Accessory.getAllUser();
                List<CTLModels.EmployeeModel> emps = Employees.GetEmployees();
                UserModel u = users.Where(w => w.name.ToLower() == user.ToLower()).FirstOrDefault();
                if (u == null)
                {
                    List<CTLModels.EmployeeModel> employees = Employees.GetEmployees();
                    CTLModels.EmployeeModel employee = employees.Where(w => w.name_en.ToLower() == user.ToLower()).FirstOrDefault();
                    u = new UserModel()
                    {
                        emp_id = employee.emp_id,
                        name = employee.name_en,
                        role = "User",
                        department = employee.department,
                    };
                }
                HttpContext.Session.SetString("Name", u.name);
                HttpContext.Session.SetString("Department", u.department);
                HttpContext.Session.SetString("Role", u.role);

                if (!u.role.Contains("Admin"))
                {
                    string position = emps.Where(w => w.emp_id == u.emp_id).Select(s => s.position).FirstOrDefault();
                    u.role = position;
                }

                return View(u);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        [HttpGet]
        public List<string> GetJobs()
        {
            List<string> jobs = Job.GetAllJobs().Select(s => s.job_id).ToList();
            jobs = jobs.OrderBy(o => o).ToList();
            return jobs;
        }

        [HttpGet]
        public IActionResult GetReportByJob(string job)
        {
            _job = job;
            List<DailyActivityModel> reports = DailyReport.GetServiceActivities(job);
            return Json(reports);
        }

        public ActionResult ExportReport()
        {
            List<DailyActivityModel> reports = DailyReport.GetServiceActivities(_job);
            //Download Excel
            var templateFileInfo = new FileInfo(Path.Combine(_hostingEnvironment.ContentRootPath, "./wwwroot/Template", "service_report.xlsx"));
            var stream = Export.ExportServiceReport(templateFileInfo, reports);
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "service_report_" + $"{_job}.xlsx");
        }
    }
}

Views/ServiceReport/Index.cshtml
@model WebENG.Models.UserModel;
@{ ViewData["Title"] = "Service Report"; }
<div class="row p-4" style="row-gap:20px">
    <div class="col-xl-12">
        <div class="card card-dark">
            <div class="card-header">
                <span class="card-title">Service Reports</span>
            </div>
            <div class="card-body">
                <form>
                    <div class="form-group row" style="row-gap:20px">

                        <div class="col-xl-3">
                            <select id="select_job" class="form-control">
                                <option value="" selected disabled>Please Select Job</option>
                            </select>
                        </div>

                        <div class="col-xl-1">
                            <button id="btn_load" type="button" class="btn btn-primary form-control elevation-1">
                                <i class="fas fa-sync"></i> Load
                            </button>
                        </div>
                        <div class="col-2 col-md-1 col-xl-1">
                            <a class="btn btn-success form-control" href="@Url.Action("ExportReport", "ServiceReport")">
                                <i class="fas fa-download"></i> Download
                            </a>
                        </div>
                    </div>
                    <hr />
                    <div class="form-group">
                        <table id="table_activity" class="table table-sm compact table-bordered table-hover text-center w-100">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Start</th>
                                    <th>Stop</th>
                                    <th>Activity</th>
                                    <th>Problem</th>
                                    <th>Solution</th>
                                    <th>Tomorrow Plan</th>
                                    <th>Note</th>
                                    <th>Action By</th>
                                    <th>Customer</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var jobs;
        var drs = [];
        var table;

        $(document).ready(async function () {
            await GetJobs();
            GenerateJobs();

            table = $('#table_activity').DataTable();
            EnableExport();
        });

        async function GetJobs() {
            await $.ajax({
                type: "GET",
                url: '@Url.Action("GetJobs", "ServiceReport")',
	            contentType: 'application/x-www-form-urlencoded',
                data: { },
                success: function (response) {
                    jobs = response;
                }
            });
        }

        function GenerateJobs() {
            var str = '<option value="" selected disabled>Please Select Job</option>';
            for (var i = 0; i < jobs.length; i++) {
                str += `<option value="${jobs[i]}">${jobs[i]}</option>`;
            }
            $('#select_job').empty();
            $('#select_job').append(str);
        }

        $('#btn_load').on('click', async function () {
            var job = $('#select_job').val();
            await GetDailyActivities(job);
            EnableExport();
            GenerateTableActivity();
        });

        async function GetDailyActivities(job) {
            await $.ajax({
                type: "GET",
                url: '@Url.Action("GetReportByJob", "ServiceReport")',
	            contentType: 'application/x-www-form-urlencoded',
                data: { job },
                success: function (response) {
                    drs = response;
                }
            });
        }

        function EnableExport() {
            if (drs.length > 0) {
                $('#btn_export').attr('disabled', false);
            } else {
                $('#btn_export').attr('disabled', true);
            }
        }

        function GenerateTableActivity() {
            var datas = [];

            for (var i = 0; i < drs.length; i++) {
                datas.push([
                    drs[i].ind,
                    drs[i].date.split("T")[0],
                    drs[i].start_time.substring(0,5),
                    drs[i].stop_time.substring(0,5),
                    drs[i].job_id + " " + drs[i].task_name,
                    drs[i].problem,
                    drs[i].solution,
                    drs[i].tomorrow_plan,
                    drs[i].note,
                    drs[i].user_name,
                    drs[i].customer
                ]);
            }

            if (table !== undefined) {
                table.destroy();
            }

            table = $('#table_activity').DataTable({
                lengthMenu: [[25,50,100,200], [25,50,100,200]],
                data: datas,
            });

            table.column(0).visible(false);
        }

    </script>
}